### ISSUE TITLE
GitHub emojis broken

### ISSUE THREAD

**Issue by justin-vanwinkle** [jedcn/reveal-ck#101]
Github Emoji Links are broken.  They are trying to be loaded from https://assets-cdn.github.com which appears to not serve emojis any longer.  I did notice however that https://github.githubassets.com works with the same paths.  I'm surprised that the cdn url would have changed...

**Comment by justin-vanwinkle** [comment]
Temp fixed by setting `asset_root: https://github.githubassets.com/images/icons` at the top level on my config.yaml

**Comment by jedcn** [comment]
:+1:

**Comment by jedcn** [comment]
Thanks for reporting! It should be a one line fix and some specs.

Will publish a change when I've got it.

Thanks for posting up the workaround with `asset_root`.

**Comment by jedcn** [comment]
Should be fixed in v3.9.2.

Thanks again!

**Comment by justin-vanwinkle** [comment]
Thank YOU!
