### ISSUE TITLE
Invalid expression: .//child::text()

### ISSUE THREAD

**Issue by tallakt** [jedcn/reveal-ck#33]
## Problem

When doing a clean install of reveal-ck, version 3.0.0, using the first slide in the tutorial, I get the error:

```
$ reveal-ck generate
Generating slides for 'slides.md'..
error: Invalid expression: .//child::text() | self::child::text()
```

## Ruby Details

```
$ ruby -v
ruby 2.1.2p95 (2014-05-08 revision 45877) [x86_64-linux]
```

## OS Details

```
$ uname -a
Linux bowser 3.16.1-1-ARCH #1 SMP PREEMPT Thu Aug 14 07:40:19 CEST 2014 x86_64 GNU/Linux
```

## Slides File

slides.md

```markdown

  # reveal-ck

  ## tutorial

  by Jed Northridge / @jedcn

  ---


  in your slides


```

**Comment by jedcn** [comment]
Great! Thank! I will take a look.

**Comment by jedcn** [comment]
Can you please try again with reveal-ck 3.0.1? It may fix the issue-- and if it doesn't-- it will help me debug it in the future. Thanks!

**Comment by kbrock** [comment]
This is an issue with `nokogiri.
It should be fixed by using a later version of html-pipeline, which limits the version of nokogiri. jch/html-pipeline#176

**Comment by jedcn** [comment]
Cool, thanks for this @kbrock. It looks like they haven't cut a release since [1.11.0](https://rubygems.org/gems/html-pipeline/versions/1.11.0). I'll check in on making the upgrade once they do.

**Comment by jedcn** [comment]
It's been a long road, but this should finally be fixed.

I took the summer off, but now I'm back.

I've upgraded to the latest compatible versions of all the gems, and this workaround should no longer be necessary.

See https://github.com/jedcn/reveal-ck/releases/tag/v3.3.0 for more info if you'd like it.

Thanks for submitting this issue!!
