### ISSUE TITLE
Default dirname to file name

### ISSUE THREAD

**Issue by kbrock** [jedcn/reveal-ck#52]
The default filename is `"slides.md"` (or similar) and the default target directory is `"slides"`.

When you choose a different file name `"myslides.md"`, it would be nice to change the default directory name to `"myslides.md"`.

The implementation is only a few lines of change. But I like having the default directory name display as `slides`. My implementation got rid of the display of the default directory. Was hoping you'd have a better suggestion.

Thanks

**Comment by jedcn** [comment]
I like the idea of:

* `slides.md` -> `slides/`
* `google-talk.md` -> `google-talk/`

That makes good sense to me.

I'll take a look shortly.

**Comment by kbrock** [comment]
:wrench: I also want support for multiple files, so that may modify this a bit (will bring in pr shortly)

**Comment by kbrock** [comment]
issue handled by 54
