### ISSUE TITLE
Include multiple slide files

### ISSUE THREAD

**Issue by kbrock** [jedcn/reveal-ck#55]
I have a bunch of urls (5-10) and `abbrs` (50) that I am sharing across a few slide decks. I'm curious how easy it would be to add "includes" into a presentation.

Ideas?
1. I like having the filename known by the cli and not by the slide file. (input multiple files better than `render`)
2. `Tilt` error messages work better when it takes in filenames vs input text. (`render` better than multiple input files)
3. A bunch of code in `reveal-cv` assumes 1 input filename. Since most of them are just a passthrough, it will probably not be a problem. I wonder if converting the filename into a template closer to the cli makes sense.
4. The cli currently uses `-f` to declare input filename. `ARGV` would be better for this use case.
5. It seems like `index.html.erb` could act a little more like rails `layout.html.erb` and use `yield`. This may reduce some code and allow a customization point. (OTOH may be a random tangent)
6. Need to have all files become part of a single tilt template. Html pipeline filters with state won't work across multiple files.

``` bash
reveal-ck # slides.md ==> slides/index.html
reveal-ck slides1.md # ==> slides1/index.html
reveal-ck slides1.md slides2.md # ==> slides1/index.html
reveal-ck -o slides slides1.md slides2.md # ==> slides/index.html
```

``` ruby
# pandoc joins multiple markdown files together.
(ARGV.empty? ? [default_file] : ARGV).map { |filename| File.read(filename) }.join("\n\n")
```

``` ruby
# alternative input
# including multiple files would not work well with yield.
<%= render('file2.md') %>
```

**Comment by jedcn** [comment]
That's interesting- I've never thought of it has something that'd be "closer" to the CLI. I always thought users would maintain a single, "master" file that would be aware of which snippets were included.

Would you want support for jumping between languages? Like:

    reveal-ck slides1.md slides2.haml slides3.slim slides4.md # ==> slides1/index.html

---

Would the following be helpful to you?

I was thinking through this issue over the weekend, and what I was thinking was more along the lines of providing the ability to explicitly include a file in `markdown`.

For example, reveal-ck already supplies a helper named `contents_of` if you're writing in a templating language like `haml` or `slim`: [description](https://relishapp.com/jedcn/reveal-ck/docs/contents-of-insert-files-into-slides), [implementation #1](https://github.com/jedcn/reveal-ck/blob/63623f75f64184846ae45150788e74cada5232ff/lib/reveal-ck/render/contents_of.rb), [implementation #2](https://github.com/jedcn/reveal-ck/blob/master/lib/reveal-ck/render/scope.rb#L6)

This lets one file include another. It's like inlining the other file and it happens before the filters are applied.

And so, what if markdown had support for `contents_of(filename)`?

The inclusion of files would be explicit-- there'd be some master file that'd be like:

```markdown

# Welcome!

---

contents_of first_part.md

---

contents_of second_part.md

---

contents_of references.md

```

And the contract would be that you get to call out the file, and it'd be included inline. And then filters would be applied.

If you wanted to troubleshoot, you might have to fall back to running reveal-ck against the single file (ala `reveal-ck --file second_part.md` or you'd have to comment out sections in the master file to limit what was being included.

One affordance that might be helpful here is that markdown allows for explicit inline html, and this `contents_of` support in markdown could allow you to keep your markdown pure and include HTML snippets as needed.

---

If this suffices, I think we're talking about adding a preprocessing step for markdown (and leaving other templating languages alone-- they are already advanced enough to inline things on their own).

And that preprocessing is invoked [here](https://github.com/jedcn/reveal-ck/blob/ef1e6b7bcfa7359c1b1c71ebb1fd5caaec87d104/lib/reveal-ck/markdown/slide_markdown.rb#L9) and [defined](https://github.com/jedcn/reveal-ck/blob/ef1e6b7bcfa7359c1b1c71ebb1fd5caaec87d104/lib/reveal-ck/markdown/pre_processor.rb) here. 

I suspect this would be pretty quick to implement: some specs, a feature or two, and concatenating some files for implementation. Maybe we output the "combined" file into the `slides/` directory so people can see the concatenated result before it's processed into `slides.html` and onto `index.html`.

**Comment by kbrock** [comment]
`contents_of` works for me.

Curious if you thought about involving involving tilt?
It may make error line numbers easier to discern.

```ruby
# not actual code
<%= File.read("second_part.md") %> # contents_of
# vs
<%= Tilt.new("second_part.md").render() %> #render
```

**Comment by jedcn** [comment]
I haven't thought about this in some time.

Are you still interested in getting it done?

Interestingly, @VinzentE asked for the same thing.

If so.. let me know and I'll get thinking about it.

I'm just getting settled at a new job, so, I should have some more time soon.

**Comment by VinzentE** [comment]
It would be great! Still haven't really found a satisfying solution to it ...

**Comment by jedcn** [comment]
I need to be honest w/ myself-- this isn't going to get fixed 🙂 . If you're watching and you really want it-- let me know or open a PR.

**Comment by kbrock** [comment]
Good for you. Close these old issues

Thanks for the great project
