### ISSUE TITLE
How to enable math plugin?

### ISSUE THREAD

**Issue by shivams** [jedcn/reveal-ck#60]
In reveal-js we have the mathJax plugin to include the maths equations in our slide. This is done by include this line in the `Reveal.Initialize`:

        { src: 'plugin/math/math.js', async: true }

How do we enable this plugin using `reveal-ck`? Is their some setting we can include in the `config.yml` for this?

**Comment by jedcn** [comment]
Hi there! Thanks for taking the time to ask.

I am not familiar with mathjax, but I believe the following sample will get you started:

Create a `slides.md` with some legitimate mathjax:

```markdown

## The Quadratic Formula

---

$$x = {-b \pm \sqrt{b^2-4ac} \over 2a}$$

```

Then create a `config.yml` like so:

```
revealjs_config:
  dependencies:
    -
      src: 'plugin/math/math.js'
      async: true
```

Then generate your slides with `reveal-ck generate`.

Please confirm if this works for you or not. I did this with a recent version of reveal-ck (3.2.0), and it should work in the most recent.

If it works.. good luck making your presentation!

**Comment by shivams** [comment]
Yes, this works perfectly. Thanks jedcn :+1: 

Further, have you documented this somewhere? I was not aware of enabling plugins this way using `reveal-ck`.

**Comment by jedcn** [comment]
So cool! Glad it worked out.

I am updating the documentation now, and I will include this exact example.

Thanks again.
