### ISSUE TITLE
error: undefined method `auto_link' for Rinku:Module when running reveal-ck generate

### ISSUE THREAD

**Issue by bgates** [jedcn/reveal-ck#61]
-that's at the command line; if I dip into irb and try to recreate what the executable does,
```ruby
irb(main):001:0> require 'reveal-ck'
=> true
irb(main):002:0> b = RevealCK::Builders::SlidesBuilder.new(user_dir: Dir.pwd,gem_dir: RevealCK.path, 
output_dir:'slides',slides_file:'slides.md')
irb(main):003:0> b.prepare && b.build
```
...which fails; the error comes from

```ruby
.../gems/html-pipeline-2.1.0/lib/html/pipeline/autolink_filter.rb:27:in `call'
```

and in the same irb session,
```ruby
rb(main):004:0> Rinku.respond_to?:auto_link
=> false
```
Now, if I require Rinku first - in a new irb session -
```ruby
❯ irb                                         
irb(main):001:0> require 'rinku'
=> true
irb(main):002:0> Rinku.respond_to?:auto_link
=> true
```
then try reveal-ck (same irb session):
```ruby
irb(main):003:0> require 'reveal-ck'
=> true
irb(main):004:0> b = RevealCK::Builders::SlidesBuilder.new(user_dir: Dir.pwd,gem_dir: RevealCK.path,
output_dir:'slides',slides_file:'slides.md')
irb(main):005:0> b.prepare && b.build
```
that works.
If I start with html/pipeline (new irb session)
```ruby
❯ irb                                        
irb(main):001:0> require 'html/pipeline'
=> true
irb(main):002:0> require 'reveal-ck'
=> true
irb(main):003:0> b = RevealCK::Builders::SlidesBuilder.new(user_dir: Dir.pwd,gem_dir: RevealCK.path,
output_dir:'slides',slides_file:'slides.md');b.prepare&&b.build
```
-that blows up. If I just refer to the HTML::Pipeline::AutolinkFilter class though
```ruby
❯ irb                                         
irb(main):001:0> require 'html/pipeline'
irb(main):002:0> HTML::Pipeline::AutolinkFilter
=> HTML::Pipeline::AutolinkFilter
irb(main):003:0> Rinku.respond_to?:auto_link
=> true
```
and from that point things work fine.
A hacky workaround is to start ```ib/reveal-ck/builders/create_slides_html.rb``` with the line
```
load 'rinku.rb'
```
but it feels like there should be something better.

**Comment by jedcn** [comment]
Hello Brian! Thanks for logging an issue.

I cannot reproduce the error you've described. I'd like to understand what's different between my system and yours.

Can you please try the following and let me know what happens?

```shell
mkdir /tmp/quick-test
cd /tmp/quick-test
echo "source 'https://rubygems.org'" > Gemfile
echo "gem 'reveal-ck', '3.3.0'" >> Gemfile
bundle install
echo "Quick Test" > slides.md
bundle exec reveal-ck generate
```

I get a newly generated set of slides that I can see when I type `open slides/index.html`.

Is that what you get?

Can you also let me know what you see when you type:

```shell
ruby --version
bundle show rinku
bundle show reveal-ck
bundle show html-pipeline
```

I see:

```shell
ruby 2.1.2p95 (2014-05-08 revision 45877) [x86_64-darwin14.0]
/opt/rubies/2.1.2/lib/ruby/gems/2.1.0/gems/rinku-1.7.3
/opt/rubies/2.1.2/lib/ruby/gems/2.1.0/gems/reveal-ck-3.3.0
/opt/rubies/2.1.2/lib/ruby/gems/2.1.0/gems/html-pipeline-2.1.0
```

**Comment by bgates** [comment]
Hi Jed! 

Your test works for me when I use `bundle exec`, but not otherwise. If I just run `reveal-ck generate` I get the same error as before. The only changes `bundle install` caused were to install new versions of minitest, pry, and nokogiri - I should say "different versions", since I had nokogiri 1.6.6.2 and this test installed 1.6.5. The three gems you asked about are the same, and my Ruby is close:

```
ruby 2.2.2p95 (2015-04-13 revision 50295) [x86_64-darwin14]
/Users/bgates/.gem/ruby/2.2.2/gems/rinku-1.7.3
/Users/bgates/.gem/ruby/2.2.2/gems/reveal-ck-3.3.0
/Users/bgates/.gem/ruby/2.2.2/gems/html-pipeline-2.1.0
```

**Comment by jedcn** [comment]
Great! I'm glad to hear that it's working and you're not blocked.

I'll take a look into why things might be failing *without* the `bundle exec` and the `Gemfile`.

**Comment by jedcn** [comment]
It took a long time, but I've published again and I don't think this is an issue anymore.

Apologies for the delay.

Please re-open if it's still happening.
