### ISSUE TITLE
Render markdown in notes

### ISSUE THREAD

**Issue by kbrock** [jedcn/reveal-ck#68]
I was hoping to submit a PR instead of an issue...

I want to have an aside with markdown in it. e.g.:

```
<aside class="metrics" markdown="1">
**fun** stuff
</aside>
```

I've tried leveraging notes (I was going to hack css for speaker notes) But I can't get it to create a node with bold in it.

```
``notes
**fun**
``
```

I've tried modifying [slide_markdown.rb](https://github.com/jedcn/reveal-ck/blob/master/lib/reveal-ck/markdown/slide_markdown.rb#L21) by adding `postprocess(preprocess(code))` but it still didn't work.

Any suggestions how to create a node with div around it (and css name)?

Thanks as always for the great tool.

**Comment by jedcn** [comment]
How does #69 look to you?

**Comment by jedcn** [comment]
Version 3.4.0 has been published here (https://rubygems.org/gems/reveal-ck/versions/3.4.0) if you'd like to try it out.
