### ISSUE TITLE
Using Webrick alternative

### ISSUE THREAD

**Issue by ginkel** [jedcn/reveal-ck#70]
Hi there,

this is more of a question than a bug. By default, reveal-ck brings up a web server based on Webrick. Unfortunately, Webrick comes with some nasty limitations when bad network connectivity is involved (it performs a lot of PTR DNS lookups). Is there an easy way (forking and patching the repo is fine as I maintain my own asciidoctor-based fork anyway) to easily substitute a different web server, e.g., Puma?

Thanks a lot,
Thilo

**Comment by kbrock** [comment]
@ginkel I use webrick to test my slides, but in production I generate and just push the static files to github pages / a webserver.

1. Does this work for you?
3. I thought user files were copied for you. it is a shame that you had to add code to copy these.

It would have been cool if slides.asciidoc could have just have used tilt to detect asciidoc and go from there. But that is probably not the whole story here.

Is reveal-asciidoc that much different from reveal-js? I'd imaging asciidoc would have a number of nice classes and things to make slide generation that much nicer

**Comment by ginkel** [comment]
Static HTML generation is a good option for production, but won't help when developing slides while on a train with crappy WiFi. ;-) What most likely contributes to the issue is that our typical setup for slide development is using a docker container, which is using an RFC1918 network and probably only introduces the reverse lookup issue (which won't happen for localhost, as 127.0.0.1 can be resolved locally without the need to query an upstream DNS server).

My current asciidoctor fork is kind of a hack (which is probably the only reason it needs a fork) that certainly could be brought in line with how upstream is doing things. Then I could probably also drop the user files hack. I was in a hurry when I needed AsciiDoc support, so I skipped some of the abstractions that `reveal-ck` is using upstream.

Creating slides from asciidoc itself is pretty neat. Effectively all you need to do is call

````
Asciidoctor.convert_file('slides.adoc',
    to_file: File.join(@output_dir, 'index.html'),
    template_dir: File.join(@gem_dir, 'files/asciidoctor-reveal.js/templates/slim')
)
````

and add asciidoctor-reveal.js as a submodule.

**Comment by jedcn** [comment]
Can you give the following a shot?

(As a general warning: I haven't done Ruby in awhile)

When I was making the `serve` command, I recall starting up the webserver with abstraction in `Rack` rather than explicitly calling out `WEBrick`. I think the underlying mechanism uses `WEBrick` if nothing else has been registered, but if alternatives like `puma` are present then they will be used.

What happens when you do the following?

Create a `Gemfile` containing:

```ruby
source 'https://rubygems.org'
gem 'puma'
gem 'reveal-ck'
```

Then run a `bundle` and a `bundle exec reveal-ck serve`.

I see `Puma starting in single mode...` in the output:

```bash
[ reveal-ck ] Starting Webserver.
Puma starting in single mode...
* Version 3.4.0 (ruby 2.1.2-p95), codename: Owl Bowl Brawl
* Min threads: 0, max threads: 16
* Environment: development
* Listening on tcp://0.0.0.0:10000
[   reload  ] Using Guardfile at /opt/rubies/2.1.2/lib/ruby/gems/2.1.0/gems/reveal-ck-3.3.0/files/reveal-ck/Guardfile.
```

From here I changed my `slides.md` around a bit, I see live updates, and then I shutdown with `CTRL-C` and I see:

```
- Gracefully stopping, waiting for requests to finish
=== puma shutdown: 2016-06-17 21:19:45 -0400 ===
- Goodbye
```

I think that's what you're looking for? Can you confirm that you can work better on the train?

**Comment by ginkel** [comment]
@jedcn Looks good, thanks a lot!

Alternatively, this commit should also do the trick for WEBrick: https://github.com/ginkel/reveal-ck/commit/58186a14369b7ca5b98eefe2350f642dbd5c3f06

**Comment by jedcn** [comment]
Okay, cool.

Regarding how to use puma as an alternative to WEBrick-- I'll add an entry to the FAQ.

Regarding https://github.com/ginkel/reveal-ck/commit/58186a14369b7ca5b98eefe2350f642dbd5c3f06, I'll  create a PR that'll bring that into master (I don't see that it hurts to have..) shortly.

---

I'm not following the idea of "user files not being copied for you." What's the issue there?

**Comment by ginkel** [comment]
@jedcn The user files issue is actually a non-issue solely introduced by the AsciiDoc patches in my fork.

Speaking of AsciiDoc, do you think it would be feasible to integrate support without the need for a fork?

**Comment by jedcn** [comment]
Sounds good.

Can you attach a trivial example of what a 5 slide presentation would look like when written in AsciiDoc?

**Comment by jedcn** [comment]
Version 3.4.0 has been published here (https://rubygems.org/gems/reveal-ck/versions/3.4.0) if you'd like to try it out.
