### ISSUE TITLE
Upgrade to Reveal v3.7.0

### ISSUE THREAD

**Issue by justin-vanwinkle** [jedcn/reveal-ck#96]
I would love to use reveal v3.7.0 with this, but it's still on v3.5.0.  Any plans to bump the version soon?  Thanks!

**Comment by justin-vanwinkle** [comment]
I realized right after I opened the issue that it is just a sub-module, so I went ahead and pointed it over to the v3.7.0 commit and opened a PR.

The things I was looking for were the arrows changing color automatically to contrast the background, the better overall aesthetics, and some other small changes that came along with the new versions.

Thanks for the quick response!

**Comment by jedcn** [comment]
Merged last night-- published just now.

Should be here:

https://rubygems.org/gems/reveal-ck/versions/3.9.0

Thanks for your help!
