### ISSUE TITLE
Serve command cannot detect change under directory slides

### ISSUE THREAD

**Issue by agate-pris** [jedcn/reveal-ck#99]
Excuse for report of issue similar to #98 in a row.

# Overview

If a file under the directory `slides` specified as the input source file, `rebuild` and `reload` will not be done even if you change the file.

If a file in a directory above the directory `slides` or another directory changed then detects it.

# Consideration and proposal

It seems to be caused by either using `slides` as the default output directory or using `slides.*` as the default input file.

It is bad that rebuild and reload does not work even if an input / output file is explicitly specified by the `--file` or` --dir` option.

If the `--file` or` --dir` option explicitly specified, detect changes in files under the `slides` directory somehow.

If it is difficult, writing `README.md` that `reveal-ck` does not detect changes in the directory `slides`.

# Detailed logs

```ps
PS D:\test> reveal-ck serve -f ./slides/foo.md -d public/slides/foo
------------------------------------------------------------
[ reveal-ck ] Serving up slide content in 'public/slides/foo/'.
[ reveal-ck ] Open your browser to 'http://localhost:10000'.
[ reveal-ck ] Press CTRL-C to stop.
------------------------------------------------------------
[ reveal-ck ] Getting Ready to Reload Browsers.
[ reveal-ck ] Getting Ready to Rebuild Slides.
[ reveal-ck ] Starting Webserver.
[   reload  ] Using Guardfile at C:/tools/ruby25/lib/ruby/gems/2.5.0/gems/reveal-ck-3.9.0/files/reveal-ck/Guardfile.
[   reload  ] Run 'gem install win32console' to use color on Windows
[   reload  ] LiveReload is waiting for a browser to connect.
[   reload  ] Guard is now watching at 'D:/test'
[   reload  ] Browser connected.
```

I changed `./slides/foo.md` in this state, but neither `rebuild` nor `reload` was done.

# Supplement

I assume that GitLab CI and GitLab Pages are to be used in combination, we have made the above directory structure.

**Comment by jedcn** [comment]
Should now be fixed in [https://rubygems.org/gems/reveal-ck/versions/3.9.1][3.9.1].

Thank you for all of your help!
